import React from 'react';
import Layout from '../../components/Layout/Layout';

function TermsAndConditions() {
    return(
        <div>
            <Layout>
                <h1 className="text-center">Termeni si Conditii</h1>
                <ol>
                    <li><h5>Lorem ipsum dolor sit.</h5></li>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere aliquid magnam modi repudiandae, deleniti ipsum incidunt, laborum, vitae tempora explicabo illo. Nobis nemo cum distinctio, facilis quas magni, voluptatem ex, placeat soluta amet delectus aliquam dicta odio saepe dolorum optio corporis natus? Reiciendis facere praesentium totam asperiores vel eum. In maiores molestias consequatur porro adipisci. Animi, vero. Dignissimos temporibus explicabo accusamus at! Adipisci nemo, nostrum reprehenderit sint dolorem eligendi consequatur animi exercitationem unde minus magnam recusandae quidem atque! Nemo sit, sapiente, fugit illo enim itaque eligendi, quibusdam odit quas culpa deserunt nostrum ipsa provident dignissimos. Voluptatibus culpa quidem sit quisquam mollitia laborum sed impedit! Rem recusandae cupiditate porro repudiandae id delectus tempore ipsam nisi, perspiciatis impedit necessitatibus a libero molestiae ea quis perferendis facilis error reprehenderit. Rem, fugiat placeat! In sed cumque repellendus praesentium, consequatur ducimus minima dolore a earum, architecto quam repellat tenetur hic alias et, quidem sequi nulla.</p>
                    <h5><li>Lorem ipsum dolor sit amet.</li></h5>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor, repellat. Praesentium ducimus quo quam illo reprehenderit molestias repudiandae odio enim at, dicta harum esse! Facere, rem! Sint laboriosam in quisquam et cum? Optio quibusdam quas dolores, atque ex in nemo tempore debitis itaque! Vel blanditiis amet, ad impedit nam omnis esse nesciunt incidunt quia maiores velit optio harum dignissimos quod sequi odit suscipit sint iure aliquam cumque! Sapiente laboriosam ut odit dicta tenetur praesentium cumque, officia animi. Inventore voluptatum, eveniet aliquam ratione eum minima maiores laudantium harum corporis, praesentium quisquam officiis laborum esse autem ad voluptatem ea nobis, provident ab recusandae veritatis. Cum sed nemo, dicta excepturi voluptate fugit modi nobis quibusdam. Cum aperiam officiis, iure ut expedita quae voluptas rem. Doloremque blanditiis velit quae error harum eaque nulla ad repudiandae mollitia earum tempore id sequi sint fugiat voluptatibus eum, esse, nihil perferendis tenetur at exercitationem qui, maiores non! Iure corporis architecto, accusamus dolor aspernatur cupiditate error itaque praesentium earum repellat consequatur, quia, adipisci quidem eius alias qui. Corrupti perspiciatis dicta porro deleniti quas dolorem repellat iste consequatur, sed possimus exercitationem perferendis debitis dolor quos eos! Asperiores mollitia quaerat laboriosam hic odio vitae veritatis quasi rem obcaecati reprehenderit modi, error necessitatibus alias sint? Et, qui ut at cumque voluptatem, minima quis sed quaerat officiis ipsam nulla quod sit. Sit repellendus expedita temporibus nostrum nisi, unde molestiae eos! Iure cum repellendus quis ex, magni porro animi facilis fugit velit magnam ratione, cumque optio consectetur veritatis nobis odio illo earum doloribus ad vel inventore! Eos recusandae quam temporibus eaque laudantium iure, impedit officiis quo a similique saepe quidem magni vel ullam. Placeat excepturi quaerat odio perspiciatis explicabo! Quasi eligendi voluptates pariatur quos facere autem atque, sapiente reiciendis quidem, quis perferendis necessitatibus quam quibusdam distinctio repudiandae. Ab temporibus odit ipsam alias impedit autem!</p>
                    <li><h5>Lorem, ipsum dolor.</h5></li>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis neque quaerat dolorem quod minima id perspiciatis assumenda! Eligendi corrupti minus aspernatur voluptatem, mollitia itaque atque id, magni temporibus cumque beatae. Aperiam numquam minus quasi praesentium, necessitatibus dolorum deserunt suscipit pariatur dolor omnis ratione, optio soluta, accusantium aliquam et? Veniam explicabo dolores doloribus rerum unde qui consequatur, earum quos beatae repudiandae cupiditate voluptatibus optio repellat sint, quidem velit dicta ut porro soluta labore voluptates. Impedit corporis sunt debitis sit. Qui, eum.</p>
                    <li><h5>Lorem ipsum dolor sit amet consectetur.</h5></li>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem provident fuga quo eos, ducimus repudiandae nostrum fugiat ut eligendi possimus voluptas similique. Repudiandae rerum ducimus in incidunt omnis quam nulla facilis libero officiis molestiae earum quaerat quos officia eius reiciendis, sit ipsum, quas culpa voluptate dignissimos quo fuga? Quibusdam, neque! Adipisci veniam facilis soluta atque praesentium nemo similique doloremque, vero provident quae! Animi, iure. Nesciunt dolorum ipsa maxime, tenetur beatae, tempore consectetur fugiat autem vitae ut veritatis assumenda ipsum iure magnam alias qui voluptates sapiente vero, inventore incidunt odit! Reprehenderit, veniam maiores quibusdam in amet excepturi consequuntur consectetur recusandae hic adipisci tenetur ad deserunt placeat quisquam mollitia inventore ab explicabo.</p>
                    <li><h5>Lorem, ipsum.</h5></li>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt eligendi nisi rerum iusto quasi, eum ratione, soluta amet dignissimos culpa dolores, minima corrupti molestiae? Harum ipsum nobis repudiandae! Accusamus, praesentium.</p>
                    <br />
                    <h6>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia accusamus voluptas, asperiores cumque suscipit quasi ratione dolorem doloribus magnam dolor adipisci quos sed! Ratione porro temporibus pariatur repellat accusamus itaque accusantium, consectetur ipsum, maxime sit praesentium nemo ea tempora. Dolore beatae architecto veniam tempora deserunt doloribus facere laboriosam voluptas, voluptatibus, optio eveniet! Quam ad recusandae ea adipisci ipsam, beatae odit laudantium voluptate suscipit? Voluptates numquam obcaecati est harum officiis saepe iure! Cumque dolorum enim soluta est eius dolores labore quas.</h6>
                    


                </ol>
            </Layout>
        </div>
    );
}

export default TermsAndConditions;